services:
  mongo:
    image: mongo:7
    container_name: asur-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - asur_mongo_data:/data/db

volumes:
  asur_mongo_data:
